### ISSUE TITLE
Google BigQuery crashes after temp file roatation

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-output-google_bigquery#10]
Migrated from: https://github.com/elastic/logstash/issues/1599

From the issue:

> hi
> after investigating an major issue i had with google_bigquery plugin i've found the following:
> every time a file is being deleted using the google_bigquery plugin, logstash crushes with the error it can't find the file.
> 
> to fix the issue i've added to the File.delete(filename) statement in both google_bigquery and google_cloud_storage ruby files the following change
> 
> File.delete(filename) if File.exist?(filename)
> it fixes the issue as files can be deleted in couple of statements prior to that roll out 
> 
> for more info: 
> https://logstash.jira.com/browse/LOGSTASH-2247
> 
> please implement the change in the upcoming versions of the product,
> Thanks,
> Dave

related to: https://github.com/logstash-plugins/logstash-output-google_cloud_storage/issues/2

**Comment by josephlewis42** [comment]
The fix for this has been released as part of logstash-output-google_bigquery version 4.0.0. 

**WARNING** 4.0.0 has breaking changes so [read the changelog](https://github.com/logstash-plugins/logstash-output-google_bigquery/blob/master/CHANGELOG.md) before upgrading to understand how they'll affect you.

The plugin can be updated with the following command

```
bin/logstash-plugin update logstash-output-google_bigquery
```
