### ISSUE TITLE
Google Bigquery table not created dynamically

### ISSUE THREAD

**Issue by sandyjoins02** [logstash-plugins/logstash-output-google_bigquery#26]
I am able to run load job successfully but the data is not visible in GBQ, though I see that the insert job is run successfully, Also Can anyone tell me if we need to create table on GBQ before shipping logs from logstash, if so, what is the table id format. 

Also, As far as I know we need to specify schema. So I just wanted to know if we can create schema dynamically.

**Comment by filipeferminiano** [comment]
any answer here? I'm with the same issue

**Comment by criccomini** [comment]
Same issue here.

**Comment by criccomini** [comment]
I believe I've found the issue with this. It is likely that the rows being inserted are malformed, and an error is being returned by BigQuery.  The plugin is swallowing the exception, rather than raising it. This is because the plugin is looking here:

https://github.com/logstash-plugins/logstash-output-google_bigquery/blob/c038430dc7b5f8536751f537896f5ae4442db6c0/lib/logstash/outputs/google_bigquery.rb#L515

It should be looking here:

```
response_body['status'].has_key?("errorResult")
```

Based on these docs:

https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load

**Comment by criccomini** [comment]
It looks like the plugin is looking for errorResult, but only in the deleter:

https://github.com/logstash-plugins/logstash-output-google_bigquery/blob/c038430dc7b5f8536751f537896f5ae4442db6c0/lib/logstash/outputs/google_bigquery.rb#L320

If the load failed, it just leaves the file there.

**Comment by criccomini** [comment]
Merged PR fixes this. Please close issue.

**Comment by criccomini** [comment]
@suyograo I think you can close this issue.

**Comment by criccomini** [comment]
lol that was fast...

**Comment by suyograo** [comment]
Haha, no, I happened to be in the slack channel where I got this notification :)
